title: 0.0
author: htlsmilework
email: htlsmilework@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 description

# social links
twitter_username: no
github_username:  htlsmilework

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
